# Generated by Django 3.2.14 on 2023-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_type_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2048)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('class_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('study_score', models.FloatField()),
                ('eat_score', models.FloatField()),
                ('sleep_score', models.FloatField()),
                ('social_score', models.FloatField()),
                ('etiquette_score', models.FloatField()),
                ('sport_score', models.FloatField()),
                ('teacher_comment', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
