# Generated by Django 3.2.14 on 2023-02-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230226_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdaily',
            name='teacher_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdaily',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
