# Generated by Django 3.2.14 on 2023-02-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230226_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdaily',
            name='date',
            field=models.DateField(),
        ),
    ]
